# _config.yaml
baseURL: "https://airoadmap.org"
languageCode: "en-GB"
defaultContentLanguage: "en"
title: "airoadmap.org: Open-Source AI Study for Enhanced Productivity & Daily Life Solutions"
disqusShortname: "DrKhan"
enableGitInfo: false
theme: "loveai-theme"

pygmentsCodeFences: true
pygmentsCodefencesGuessSyntax: true
pygmentsUseClasses: true
enable_anchor_links: true

menu:
  main:
    - name: "Home"
      url: "/"
      weight: 1
    - name: "Documents"
      url: "/docs/"
      weight: 2

params:
  description: "airoadmap.org is an open-source AI study designed to provide insights and practical tools for enhancing productivity and simplifying daily tasks."
  homeMetaContent: "Explore airoadmap.org's open-source AI study, offering data-driven insights and solutions to improve productivity and daily life for individuals and small businesses."
  homepage_button_link: "/docs/"
  homepage_button_text: "Read the AI Roadmap Whitepaper"

  logo:
      standard: "images/airoadmap-logo2.svg"
      mobile: "images/airoadmap-logo2.svg"
  
  footer:
    copyright_text: "© 2024 airoadmap.org | Author: <a href='https://wajidkhan.info'>Dr Wajid Khan</a>"
  dateFormat: "24 Jan 2024"
